switch("path", "$projectDir/stubs")
switch("path", "$projectDir/../deps/arm_cores")
switch("path", "$projectDir/../deps/RTT")
switch("path", "$projectDir/../src")
switch("path", "$projectDir/../src/krnlpkg")
switch("define", "domain=test")